name: Python application test

on: [push, pull_request]

jobs:
  test_math:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12.1', '3.11.7', '3.10.13']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run math tests
      run: pytest tests/test_math.py

  test_web_chrome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12.1', '3.11.7', '3.10.13']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Installing package list
      run: apt list --installed

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Installing all necessary packages
      run: pip install -r requirements.txt

    - name: GUI tests
      uses: GabrielBB/xvfb-action@v1.6
      with:
        run: pytest tests/test_web.py::test_my_first_chrome_selenium_test
